receivers:
  otlp:
    protocols:
      grpc:
      http:
          
exporters:
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true    
  logging:
    verbosity: detailed

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

connectors:
  spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [otlp,logging, spanmetrics]
      exporters: [logging, spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      # processors: [filter, batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]